# Generated by Django 3.2.15 on 2022-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rollno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
