# Generated by Django 3.2.15 on 2022-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='percentage',
            field=models.CharField(default='', max_length=150),
        ),
    ]
