# Generated by Django 3.2.15 on 2022-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.IntegerField(),
        ),
    ]
