# Generated by Django 3.2.15 on 2022-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220911_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
