# Generated by Django 3.2.15 on 2022-10-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rollno',
        ),
    ]
