# Generated by Django 3.2.15 on 2023-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230222_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicform',
            name='sem',
            field=models.CharField(max_length=50),
        ),
    ]
