# Generated by Django 3.2.15 on 2023-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
