# Generated by Django 3.2.15 on 2023-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230315_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='branch',
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='myclass',
            field=models.CharField(default=[], max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sem',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
