# Generated by Django 3.2.15 on 2023-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20230319_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.CharField(default=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.CharField(default=[], max_length=150),
        ),
    ]
