# Generated by Django 4.2 on 2023-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230319_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=100)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('branch', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('s1_q', models.IntegerField(default=0)),
                ('suggestion', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
