# Generated by Django 4.2 on 2023-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_newfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newfeedback',
            old_name='s1_q',
            new_name='s1_q1',
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s1_q7',
            field=models.IntegerField(default=0),
        ),
    ]
