# Generated by Django 4.2 on 2023-04-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_s1_q_newfeedback_s1_q1_newfeedback_s1_q2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newfeedback',
            old_name='subject',
            new_name='s1_subject_name',
        ),
        migrations.RenameField(
            model_name='newfeedback',
            old_name='teacher_name',
            new_name='s1_teacher_name',
        ),
    ]
