# Generated by Django 4.2 on 2023-04-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_subject_newfeedback_s1_subject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newfeedback',
            old_name='suggestion',
            new_name='s1_suggestion',
        ),
    ]
