# Generated by Django 4.2 on 2023-04-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_suggestion_newfeedback_s1_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_q7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_subject_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_suggestion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s2_teacher_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
