# Generated by Django 4.2 on 2023-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_newfeedback_s3_q1_newfeedback_s3_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_q7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_subject_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_suggestion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s4_teacher_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_q7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_subject_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_suggestion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='s5_teacher_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
