# Generated by Django 4.2 on 2023-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_newfeedback_s4_q1_newfeedback_s4_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeedback',
            name='academic_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
