# Generated by Django 4.2 on 2023-04-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_newfeedback_academic_year_newfeedback_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewFeedback',
            new_name='TheoryFeedback',
        ),
    ]
