# Generated by Django 4.1.1 on 2023-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_practicalfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default=[], max_length=200)),
                ('myclass', models.CharField(default=[], max_length=200)),
                ('sem', models.CharField(default=[], max_length=200)),
                ('branch', models.CharField(default=[], max_length=200)),
                ('q1', models.CharField(default=[], max_length=150)),
                ('q2', models.CharField(default=[], max_length=150)),
                ('q3', models.CharField(default=[], max_length=150)),
                ('q4', models.CharField(default=[], max_length=150)),
                ('q5', models.CharField(default=[], max_length=150)),
                ('q6', models.CharField(default=[], max_length=150)),
                ('q7', models.CharField(default=[], max_length=150)),
                ('suggestion', models.CharField(default=[], max_length=150)),
                ('date', models.DateField()),
            ],
        ),
    ]
