# Generated by Django 4.1.1 on 2023-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicform',
            name='feedbacktype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
