# Generated by Django 4.1.4 on 2023-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_academicform_feedbacktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=[], max_length=200)),
                ('email', models.CharField(default=[], max_length=200)),
                ('comments', models.CharField(default=[], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=[], max_length=200)),
                ('email', models.CharField(default=[], max_length=200)),
                ('comments', models.CharField(default=[], max_length=200)),
            ],
        ),
    ]
