# Generated by Django 4.1.4 on 2023-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alumnifeedback_parentsfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnifeedback',
            name='department',
            field=models.CharField(default=[], max_length=50),
        ),
        migrations.AddField(
            model_name='alumnifeedback',
            name='passout_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumnifeedback',
            name='email',
            field=models.CharField(default=[], max_length=50),
        ),
    ]
