# Generated by Django 4.1.4 on 2023-04-25 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alumnifeedback_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnifeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 21, 22, 42, 583548)),
        ),
        migrations.AddField(
            model_name='parentsfeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 21, 22, 42, 582549)),
        ),
    ]
