# Generated by Django 4.1.4 on 2023-04-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alumnifeedback_date_parentsfeedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnifeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 21, 27, 58, 400437)),
        ),
        migrations.AlterField(
            model_name='parentsfeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 21, 27, 58, 399438)),
        ),
    ]
