# Generated by Django 4.1.4 on 2023-04-25 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_alumnifeedback_date_alter_parentsfeedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnifeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 22, 44, 1, 36518)),
        ),
        migrations.AlterField(
            model_name='parentsfeedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 22, 44, 1, 36518)),
        ),
    ]
